---
name: "RunScripts"
guid: "616552f9-8355-4737-bbe0-8217f9e8ea14"
version: "1.0.0.0"
targetAbi: "10.7.0.0"
framework: "net5.0"
overview: "Run scripts after events like playback start and stop"
description: >
  Run Scripts is a Jellyfin Plugin that let's you run custom
  scripts after events like playback start and stop.
category: "General"
owner: "lmaonator"
artifacts:
- "Jellyfin.Plugin.RunScripts.dll"
changelog: >
  changelog
